test: Fix missing tokio test macro dependency
The tests make use of the `#[tokio::test]` macro, but the tokio dependency default feature does not include them. Running cargo test fails.

By including the `macros` feature on the tokio dependency, cargo test will work.

---

cargo test fails with

```
error[E0433]: failed to resolve: could not find `test` in `tokio`
   --> src\scheduled_tasks.rs:295:12
    |
295 |   #[tokio::test]
    |            ^^^^ could not find `test` in `tokio`
```